inputs:
  java_version:
    description: 'Java version'
    required: false
    default: '17'

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
      with:
        cache-disabled: false

