default_platform(:ios)

platform :ios do
  desc "Export a signed white-label React Native/Expo IPA from an existing xcarchive"
  lane :export_saas_ipa do |options|
    archive_path        = options[:archive_path]
    scheme_name         = options[:scheme_name]
    team_id             = options[:team_id]
    profile_uuid        = options[:profile_uuid]
    bundle_id           = options[:bundle_id]
    method              = options[:method] || "app-store"
    method = "ad-hoc" if method == "adhoc"
    method = "app-store" if method == "appstore"
    keychain_path       = options[:keychain_path]

    UI.message "📦 Exporting IPA from Archive: #{archive_path} for Scheme: #{scheme_name} using keychain: #{keychain_path}"

    build_ios_app(
      archive_path: archive_path,
      skip_build_archive: true,
      include_symbols: false,
      scheme: scheme_name,
      output_directory: "./build",
      output_name: "#{scheme_name}.ipa",
      export_method: method,
      export_options: {
        signingStyle: "manual",
        teamID: team_id,
        uploadSymbols: false,
        provisioningProfiles: {
          bundle_id => profile_uuid
        }
      }
    )
  end
end
